spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/onboarding
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: onboarding-service
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      type: single
